"""Stub file for staff.duration module."""

from __future__ import annotations
from fractions import Fraction
from typing import Callable, Union

MAX_DURATION_DENOMINATOR: int
MAX_DURATION_DOTS: int
MIN_TEMPO_BPM: int
MAX_TEMPO_BPM: int

class Duration:
    denominator: int
    dots: int
    is_rest: bool
    
    def __init__(self, denominator: int, dots: int = 0, is_rest: bool = False) -> None: ...
    
    @property
    def decimal(self) -> float: ...
    
    @property
    def fraction(self) -> Fraction: ...
    
    def milliseconds(self, tempo: Tempo) -> float: ...
    
    def __gt__(self, other: Duration) -> bool: ...
    def __lt__(self, other: Duration) -> bool: ...
    def __ge__(self, other: Duration) -> bool: ...
    def __le__(self, other: Duration) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    
    def __add__(self, other: Duration) -> Duration: ...
    def __radd__(self, other: Union[int, Duration]) -> Duration: ...
    def __sub__(self, other: Duration) -> Duration: ...
    def __mul__(self, other: Union[int, float]) -> Duration: ...
    def __rmul__(self, other: Union[int, float]) -> Duration: ...
    def __truediv__(self, other: Union[int, float]) -> Duration: ...

class Tuplet:
    divisions: int
    duration: Duration
    
    def __init__(self, divisions: int, duration: Duration) -> None: ...
    
    def to_milliseconds(self, tempo: Tempo) -> list[float]: ...

class Tempo:
    bpm: int
    beat: Duration
    
    def __init__(self, bpm: int, beat: Duration = ...) -> None: ...
    
    @property
    def beat_milliseconds(self) -> float: ...