"""Stub file for staff.pitch module."""

from __future__ import annotations
from typing import Callable, Optional, Union

class Diapason:
    reference_midi_number: int
    reference_hertz: float
    
    def __init__(self, reference_midi_number: int = 69, reference_hertz: float = 440.0) -> None: ...

class Frequency:
    hertz: float
    
    def __init__(self, hertz: float) -> None: ...
    
    def to_midi(
        self,
        midi_bend_range: int = 200,
        diapason: Diapason = ...,
        octave_divs: int = 12,
    ) -> MIDIPitch: ...
    
    def cents_distance(self, other: Frequency) -> Cents: ...
    def plus_cents(self, cents: Cents) -> Frequency: ...
    
    def __gt__(self, other: Frequency) -> bool: ...
    def __lt__(self, other: Frequency) -> bool: ...
    def __ge__(self, other: Frequency) -> bool: ...
    def __le__(self, other: Frequency) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    
    def __add__(self, other: Frequency) -> Frequency: ...
    def __sub__(self, other: Frequency) -> Frequency: ...
    def __mul__(self, other: Union[int, float]) -> Frequency: ...
    def __rmul__(self, other: Union[int, float]) -> Frequency: ...
    def __truediv__(self, other: Union[int, float]) -> Frequency: ...
    def __floordiv__(self, other: Union[int, float]) -> Frequency: ...
    def __round__(self, ndigits: int) -> Frequency: ...

class Cents:
    cents: float
    
    def __init__(self, cents: float) -> None: ...
    
    @property
    def proportion_of_octave(self) -> float: ...
    
    def to_midi_bend(self, bend_range: int = 200) -> MIDIBend: ...
    
    def __gt__(self, other: Cents) -> bool: ...
    def __lt__(self, other: Cents) -> bool: ...
    def __ge__(self, other: Cents) -> bool: ...
    def __le__(self, other: Cents) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    
    def __add__(self, other: Cents) -> Cents: ...
    def __sub__(self, other: Cents) -> Cents: ...
    def __mul__(self, other: Union[int, float]) -> Cents: ...
    def __rmul__(self, other: Union[int, float]) -> Cents: ...
    def __truediv__(self, other: Union[int, float]) -> Cents: ...
    def __floordiv__(self, other: Union[int, float]) -> Cents: ...
    def __round__(self, ndigits: Optional[int] = None) -> Cents: ...

class MIDIBend:
    bend: int
    bend_range: int
    
    def __init__(self, bend: int = 0, bend_range: int = 200) -> None: ...
    
    @property
    def cents(self) -> Cents: ...

class MIDIPitch:
    number: int
    bend: MIDIBend
    diapason: Diapason
    octave_divs: int
    
    def __init__(
        self,
        number: int,
        bend: MIDIBend = ...,
        diapason: Diapason = ...,
        octave_divs: int = 12,
    ) -> None: ...
    
    def __hash__(self) -> int: ...
    
    @property
    def number_precise(self) -> float: ...
    
    @property
    def frequency(self) -> Frequency: ...
    
    @property
    def pitch_class(self) -> int: ...
    
    @property
    def pitch_class_precise(self) -> MIDIPitch: ...
    
    @classmethod
    def from_string(cls, pitch: str, c4_number: int = 60) -> MIDIPitch: ...
    
    def octave_up(self) -> MIDIPitch: ...
    def octave_down(self) -> MIDIPitch: ...
    
    def __gt__(self, other: MIDIPitch) -> bool: ...
    def __lt__(self, other: MIDIPitch) -> bool: ...
    def __ge__(self, other: MIDIPitch) -> bool: ...
    def __le__(self, other: MIDIPitch) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...