site_name: staff
repo_url: https://github.com/inegm/staff
nav:
  - about: "index.md"
  - API:
      - pitch: "api/pitch.md"
      - duration: "api/duration.md"
      - numerical: "api/numerical.md"
      - patterns:
        - duration: "api/patterns/duration.md"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            annotations_path: brief
            show_bases: true
            show_docstring_examples: true