"""Stub file for staff.orchestration.voicing module."""

from __future__ import annotations
from typing import List, Union, Tuple, Optional
from .instrument import Instrument
from ..pitch import MIDIPitch

class VoicedPitch:
    instrument: Instrument
    pitch: MIDIPitch
    
    def __init__(self, instrument: Instrument, pitch: MIDIPitch) -> None: ...
    
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class VoicedChord:
    def __init__(self, voices: List[VoicedPitch]) -> None: ...
    
    @property
    def voices(self) -> List[VoicedPitch]: ...
    
    @property
    def spread(self) -> float: ...
    
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __gt__(self, other: VoicedChord) -> bool: ...
    def __lt__(self, other: VoicedChord) -> bool: ...
    def __ge__(self, other: VoicedChord) -> bool: ...
    def __le__(self, other: VoicedChord) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    
    def contains_crossing(self) -> bool: ...
    def contains_doubling(self) -> bool: ...

def voice_pitches(
    pitches: List[MIDIPitch],
    instruments: List[Instrument],
    spread: float = 0.5,
) -> Optional[VoicedChord]: ...

def find_all_voicings(
    pitches: Tuple[MIDIPitch, ...],
    instruments: Tuple[Instrument, ...],
) -> List[VoicedChord]: ...

def find_closest_voicing(
    voicing: VoicedChord,
    candidates: Tuple[VoicedChord, ...],
) -> VoicedChord: ...