from typing import Optional

from staff.db import DB_PATH
from staff.db.instruments import store_instrument
from staff.orchestration.instrument import Articulation, Instrument, InstrumentRange
from staff.pitch import MIDIPitch


def populate_instruments(db_path: str = DB_PATH) -> None:
    """Populate the database with instruments.

    Args:
        db_path: The path to the database.
    """
    instruments = [
        # Strings
        #   Violins 1 Leader
        Instrument(
            name="Violins 1 Leader",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("G3"),
                top=MIDIPitch.from_string("C#7"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
            ],
            is_continuous=True,
            abbreviation="Vln. 1 Ldr.",
            category="BBC Symphony Orchestra",
            description="The leader of the first violin section of the BBC Symphony Orchestra.",
        ),
        #   Violins 1
        Instrument(
            name="Violins 1",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("G3"),
                top=MIDIPitch.from_string("C#7"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Long marcato attack",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A long, sustained articulation with an accented tone.",
                ),
                Articulation(
                    name="Tremolo sul pont",
                    key_switch=MIDIPitch.from_string("E0"),
                    abbreviation="Trem. sul pont.",
                    description="A short, detached articulation with a tremolo effect produced by playing near the bridge.",
                ),
                Articulation(
                    name="Tremolo CS",
                    key_switch=MIDIPitch.from_string("F0"),
                    abbreviation="Trem. CS",
                    description="A short, detached articulation with a tremolo effect produced by playing with a mute.",
                ),
                Articulation(
                    name="Long sul pont",
                    key_switch=MIDIPitch.from_string("F#0"),
                    abbreviation="Sul pont.",
                    description="A long, sustained articulation with a tone produced by playing near the bridge.",
                ),
                Articulation(
                    name="Spiccato con sordino",
                    key_switch=MIDIPitch.from_string("G0"),
                    abbreviation="Spicc. con sord.",
                    description="A short, bouncy articulation with a mute.",
                ),
            ],
            is_continuous=True,
            abbreviation="Vln. 1",
            category="BBC Symphony Orchestra",
            description="The first violin section of the BBC Symphony Orchestra.",
        ),
        #   Violins 2 Leader
        Instrument(
            name="Violins 2 Leader",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("G3"),
                top=MIDIPitch.from_string("C#7"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
            ],
            is_continuous=True,
            abbreviation="Vln. 2 Ldr.",
            category="BBC Symphony Orchestra",
            description="The leader of the second violin section of the BBC Symphony Orchestra.",
        ),
        #   Violins 2
        Instrument(
            name="Violins 2",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("G3"),
                top=MIDIPitch.from_string("C#7"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Long marcato attack",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A long, sustained articulation with an accented tone.",
                ),
                Articulation(
                    name="Tremolo sul pont",
                    key_switch=MIDIPitch.from_string("E0"),
                    abbreviation="Trem. sul pont.",
                    description="A short, detached articulation with a tremolo effect produced by playing near the bridge.",
                ),
                Articulation(
                    name="Tremolo CS",
                    key_switch=MIDIPitch.from_string("F0"),
                    abbreviation="Trem. CS",
                    description="A short, detached articulation with a tremolo effect produced by playing with a mute.",
                ),
                Articulation(
                    name="Long sul pont",
                    key_switch=MIDIPitch.from_string("F#0"),
                    abbreviation="Sul pont.",
                    description="A long, sustained articulation with a tone produced by playing near the bridge.",
                ),
                Articulation(
                    name="Spiccato con sordino",
                    key_switch=MIDIPitch.from_string("G0"),
                    abbreviation="Spicc. con sord.",
                    description="A short, bouncy articulation with a mute.",
                ),
            ],
            is_continuous=True,
            abbreviation="Vln. 2",
            category="BBC Symphony Orchestra",
            description="The second violin section of the BBC Symphony Orchestra.",
        ),
        #   Violas Leader
        Instrument(
            name="Violas Leader",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("C3"),
                top=MIDIPitch.from_string("F#6"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
            ],
            is_continuous=True,
            abbreviation="Vla. Ldr.",
            category="BBC Symphony Orchestra",
            description="The leader of the viola section of the BBC Symphony Orchestra.",
        ),
        #   Violas
        Instrument(
            name="Violas",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("G3"),
                top=MIDIPitch.from_string("C#7"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Long marcato attack",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A long, sustained articulation with an accented tone.",
                ),
                Articulation(
                    name="Tremolo sul pont",
                    key_switch=MIDIPitch.from_string("E0"),
                    abbreviation="Trem. sul pont.",
                    description="A short, detached articulation with a tremolo effect produced by playing near the bridge.",
                ),
                Articulation(
                    name="Tremolo CS",
                    key_switch=MIDIPitch.from_string("F0"),
                    abbreviation="Trem. CS",
                    description="A short, detached articulation with a tremolo effect produced by playing with a mute.",
                ),
                Articulation(
                    name="Long sul pont",
                    key_switch=MIDIPitch.from_string("F#0"),
                    abbreviation="Sul pont.",
                    description="A long, sustained articulation with a tone produced by playing near the bridge.",
                ),
                Articulation(
                    name="Spiccato con sordino",
                    key_switch=MIDIPitch.from_string("G0"),
                    abbreviation="Spicc. con sord.",
                    description="A short, bouncy articulation with a mute.",
                ),
            ],
            is_continuous=True,
            abbreviation="Vla.",
            category="BBC Symphony Orchestra",
            description="The viola section of the BBC Symphony Orchestra.",
        ),
        #   Celli Leader
        Instrument(
            name="Celli Leader",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("C2"),
                top=MIDIPitch.from_string("A#5"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
            ],
            is_continuous=True,
            abbreviation="Vc. Ldr.",
            category="BBC Symphony Orchestra",
            description="The leader of the cello section of the BBC Symphony Orchestra.",
        ),
        #   Celli
        Instrument(
            name="Celli",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("C2"),
                top=MIDIPitch.from_string("A#5"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Long marcato attack",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A long, sustained articulation with an accented tone.",
                ),
                Articulation(
                    name="Tremolo sul pont",
                    key_switch=MIDIPitch.from_string("E0"),
                    abbreviation="Trem. sul pont.",
                    description="A short, detached articulation with a tremolo effect produced by playing near the bridge.",
                ),
                Articulation(
                    name="Tremolo CS",
                    key_switch=MIDIPitch.from_string("F0"),
                    abbreviation="Trem. CS",
                    description="A short, detached articulation with a tremolo effect produced by playing with a mute.",
                ),
                Articulation(
                    name="Long sul pont",
                    key_switch=MIDIPitch.from_string("F#0"),
                    abbreviation="Sul pont.",
                    description="A long, sustained articulation with a tone produced by playing near the bridge.",
                ),
                Articulation(
                    name="Spiccato con sordino",
                    key_switch=MIDIPitch.from_string("G0"),
                    abbreviation="Spicc. con sord.",
                    description="A short, bouncy articulation with a mute.",
                ),
            ],
            is_continuous=True,
            abbreviation="Vc.",
            category="BBC Symphony Orchestra",
            description="The cello section of the BBC Symphony Orchestra.",
        ),
        #   Bass Leader
        Instrument(
            name="Bass Leader",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("C1"),
                top=MIDIPitch.from_string("F#3"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
            ],
            is_continuous=True,
            abbreviation="Cb. Ldr.",
            category="BBC Symphony Orchestra",
            description="The leader of the double bass section of the BBC Symphony Orchestra.",
        ),
        #   Basses
        Instrument(
            name="Basses",
            section="Strings",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("C1"),
                top=MIDIPitch.from_string("F#3"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Con Sordino",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Con Sord.",
                    description="A smooth, connected articulation with a mute.",
                ),
                Articulation(
                    name="Flautando",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Flaut.",
                    description="A smooth, connected articulation with a flute-like tone.",
                ),
                Articulation(
                    name="Spiccato",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Spicc.",
                    description="A short, bouncy articulation.",
                ),
                Articulation(
                    name="Staccato",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Stac.",
                    description="A short, detached articulation.",
                ),
                Articulation(
                    name="Pizzicato",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Pizz.",
                    description="A short, detached articulation with a plucked tone.",
                ),
                Articulation(
                    name="Col Legno",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Col Leg.",
                    description="A short, detached articulation with a tone produced by striking the strings with the wood of the bow.",
                ),
                Articulation(
                    name="Tremolo",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trem.",
                    description="A short, detached articulation with a tremolo effect.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long sul tasto",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Sul tasto",
                    description="A long, sustained articulation with a tone produced by playing over the fingerboard.",
                ),
                Articulation(
                    name="Long harmonics",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Harmonics",
                    description="A long, sustained articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Short harmonics",
                    key_switch=MIDIPitch.from_string("C#0"),
                    abbreviation="Harmonics",
                    description="A short, detached articulation with a tone produced by lightly touching the string at a harmonic node.",
                ),
                Articulation(
                    name="Bartok pizzicato",
                    key_switch=MIDIPitch.from_string("D0"),
                    abbreviation="Bartok pizz.",
                    description="A short, detached articulation with a tone produced by plucking the string and allowing it to snap back against the fingerboard.",
                ),
                Articulation(
                    name="Long marcato attack",
                    key_switch=MIDIPitch.from_string("D#0"),
                    abbreviation="Marc.",
                    description="A long, sustained articulation with an accented tone.",
                ),
                Articulation(
                    name="Tremolo sul pont",
                    key_switch=MIDIPitch.from_string("E0"),
                    abbreviation="Trem. sul pont.",
                    description="A short, detached articulation with a tremolo effect produced by playing near the bridge.",
                ),
                Articulation(
                    name="Tremolo CS",
                    key_switch=MIDIPitch.from_string("F0"),
                    abbreviation="Trem. CS",
                    description="A short, detached articulation with a tremolo effect produced by playing with a mute.",
                ),
                Articulation(
                    name="Long sul pont",
                    key_switch=MIDIPitch.from_string("F#0"),
                    abbreviation="Sul pont.",
                    description="A long, sustained articulation with a tone produced by playing near the bridge.",
                ),
                Articulation(
                    name="Spiccato con sordino",
                    key_switch=MIDIPitch.from_string("G0"),
                    abbreviation="Spicc. con sord.",
                    description="A short, bouncy articulation with a mute.",
                ),
            ],
            is_continuous=True,
            abbreviation="Cb.",
            category="BBC Symphony Orchestra",
            description="The double bass section of the BBC Symphony Orchestra.",
        ),
        # Brass
        #   Horn
        Instrument(
            name="Horn",
            section="Brass",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("E2"),
                top=MIDIPitch.from_string("F5"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Staccatisimo",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Stacc.",
                    description="A short, detached articulation with a very short duration.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
                Articulation(
                    name="Long cuivre",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Cuivre",
                    description="A long, sustained articulation with a brassy tone.",
                ),
                Articulation(
                    name="Long sfz",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Sfz",
                    description="A long, sustained articulation with a sudden, accented onset.",
                ),
                Articulation(
                    name="Long flutter",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Flutter",
                    description="A long, sustained articulation with a fluttering tone.",
                ),
                Articulation(
                    name="Multi-tongue",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Multi-tongue",
                    description="A short, detached articulation with a fluttering tone produced by tonguing the reed multiple times.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long (muted)",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Long (muted)",
                    description="A long, sustained articulation with a mute.",
                ),
                Articulation(
                    name="Staccatisimo (muted)",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Stacc. (muted)",
                    description="A short, detached articulation with a very short duration and a mute.",
                ),
                Articulation(
                    name="Marcato (muted)",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Marc. (muted)",
                    description="A short, detached articulation with an accented tone and a mute.",
                ),
            ],
            is_continuous=False,
            abbreviation="Hn. Ldr.",
            category="BBC Symphony Orchestra",
            description="The leader of the horn section of the BBC Symphony Orchestra.",
        ),
        #   Horns a4
        Instrument(
            name="Horns a4",
            section="Brass",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("E2"),
                top=MIDIPitch.from_string("F5"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Staccatisimo",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Stacc.",
                    description="A short, detached articulation with a very short duration.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
                Articulation(
                    name="Long cuivre",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Cuivre",
                    description="A long, sustained articulation with a brassy tone.",
                ),
                Articulation(
                    name="Long sfz",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Sfz",
                    description="A long, sustained articulation with a sudden, accented onset.",
                ),
                Articulation(
                    name="Long flutter",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Flutter",
                    description="A long, sustained articulation with a fluttering tone.",
                ),
                Articulation(
                    name="Multi-tongue",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Multi-tongue",
                    description="A short, detached articulation with a fluttering tone produced by tonguing the reed multiple times.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long (muted)",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Long (muted)",
                    description="A long, sustained articulation with a mute.",
                ),
                Articulation(
                    name="Staccatisimo (muted)",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Stacc. (muted)",
                    description="A short, detached articulation with a very short duration and a mute.",
                ),
                Articulation(
                    name="Marcato (muted)",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Marc. (muted)",
                    description="A short, detached articulation with an accented tone and a mute.",
                ),
            ],
            is_continuous=False,
            abbreviation="Hn.",
            category="BBC Symphony Orchestra",
            description="The horn section of the BBC Symphony Orchestra.",
        ),
        #   Trumpet
        Instrument(
            name="Trumpet",
            section="Brass",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("E3"),
                top=MIDIPitch.from_string("C6"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Staccatisimo",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Stacc.",
                    description="A short, detached articulation with a very short duration.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
                Articulation(
                    name="Long cuivre",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Cuivre",
                    description="A long, sustained articulation with a brassy tone.",
                ),
                Articulation(
                    name="Long sfz",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Sfz",
                    description="A long, sustained articulation with a sudden, accented onset.",
                ),
                Articulation(
                    name="Long flutter",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Flutter",
                    description="A long, sustained articulation with a fluttering tone.",
                ),
                Articulation(
                    name="Multi-tongue",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Multi-tongue",
                    description="A short, detached articulation with a fluttering tone produced by tonguing the reed multiple times.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long (muted)",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Long (muted)",
                    description="A long, sustained articulation with a mute.",
                ),
                Articulation(
                    name="Staccatisimo (muted)",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Stacc. (muted)",
                    description="A short, detached articulation with a very short duration and a mute.",
                ),
                Articulation(
                    name="Marcato (muted)",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Marc. (muted)",
                    description="A short, detached articulation with an accented tone and a mute.",
                ),
            ],
            is_continuous=False,
            abbreviation="Tpt. Ldr.",
            category="BBC Symphony Orchestra",
            description="The leader of the trumpet section of the BBC Symphony Orchestra.",
        ),
        #   Trumpets a3
        Instrument(
            name="Trumpets a3",
            section="Brass",
            range=InstrumentRange(
                bottom=MIDIPitch.from_string("E3"),
                top=MIDIPitch.from_string("C6"),
            ),
            articulations=[
                Articulation(
                    name="Legato",
                    key_switch=MIDIPitch.from_string("C-1"),
                    abbreviation="Leg.",
                    description="A smooth, connected articulation.",
                ),
                Articulation(
                    name="Long",
                    key_switch=MIDIPitch.from_string("C#-1"),
                    abbreviation="Long",
                    description="A long, sustained articulation.",
                ),
                Articulation(
                    name="Staccatisimo",
                    key_switch=MIDIPitch.from_string("D-1"),
                    abbreviation="Stacc.",
                    description="A short, detached articulation with a very short duration.",
                ),
                Articulation(
                    name="Marcato",
                    key_switch=MIDIPitch.from_string("D#-1"),
                    abbreviation="Marc.",
                    description="A short, detached articulation with an accented tone.",
                ),
                Articulation(
                    name="Long cuivre",
                    key_switch=MIDIPitch.from_string("E-1"),
                    abbreviation="Cuivre",
                    description="A long, sustained articulation with a brassy tone.",
                ),
                Articulation(
                    name="Long sfz",
                    key_switch=MIDIPitch.from_string("F-1"),
                    abbreviation="Sfz",
                    description="A long, sustained articulation with a sudden, accented onset.",
                ),
                Articulation(
                    name="Long flutter",
                    key_switch=MIDIPitch.from_string("F#-1"),
                    abbreviation="Flutter",
                    description="A long, sustained articulation with a fluttering tone.",
                ),
                Articulation(
                    name="Multi-tongue",
                    key_switch=MIDIPitch.from_string("G-1"),
                    abbreviation="Multi-tongue",
                    description="A short, detached articulation with a fluttering tone produced by tonguing the reed multiple times.",
                ),
                Articulation(
                    name="Trill major 2nd",
                    key_switch=MIDIPitch.from_string("G#-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a major 2nd above.",
                ),
                Articulation(
                    name="Trill minor 2nd",
                    key_switch=MIDIPitch.from_string("A-1"),
                    abbreviation="Trill",
                    description="A trill between the note and the note a minor 2nd above.",
                ),
                Articulation(
                    name="Long (muted)",
                    key_switch=MIDIPitch.from_string("A#-1"),
                    abbreviation="Long (muted)",
                    description="A long, sustained articulation with a mute.",
                ),
                Articulation(
                    name="Staccatisimo (muted)",
                    key_switch=MIDIPitch.from_string("B-1"),
                    abbreviation="Stacc. (muted)",
                    description="A short, detached articulation with a very short duration and a mute.",
                ),
                Articulation(
                    name="Marcato (muted)",
                    key_switch=MIDIPitch.from_string("C0"),
                    abbreviation="Marc. (muted)",
                    description="A short, detached articulation with an accented tone and a mute.",
                ),
            ],
            is_continuous=False,
            abbreviation="Tpt.",
            category="BBC Symphony Orchestra",
            description="The trumpet section of the BBC Symphony Orchestra.",
        ),
    ]
    for instrument in instruments:
        store_instrument(instrument=instrument, db_path=db_path)
