"""Stub file for staff.patterns.duration module."""

from __future__ import annotations
from typing import List, Union, overload
from ..duration import Duration, Tempo
from .pattern import _BasePattern

class DurationPattern(_BasePattern):
    def __init__(self, pattern: List[Duration]) -> None: ...
    
    def append(self, value: Duration) -> DurationPattern: ...
    def prepend(self, value: Duration) -> DurationPattern: ...
    def milliseconds(self, tempo: Tempo) -> float: ...
    def retrograde(self) -> DurationPattern: ...
    def rotate(self, factor: int) -> DurationPattern: ...
    def prolate(self, factor: Union[int, float]) -> DurationPattern: ...
    def permutations(self) -> List[DurationPattern]: ...
    
    def __repr__(self) -> str: ...
    def __mul__(self, other: float) -> DurationPattern: ...
    def __truediv__(self, other: float) -> DurationPattern: ...
    
    # Inherited from _BasePattern
    def to_list(self) -> List[Duration]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    
    @overload
    def __getitem__(self, key: int) -> Duration: ...
    @overload 
    def __getitem__(self, key: slice) -> List[Duration]: ...