"""Stub file for staff.patterns.pattern module."""

from __future__ import annotations
from typing import Any, List, Optional, overload

class _BasePattern:
    def __init__(self, pattern: Optional[List[Any]] = None) -> None: ...
    
    def to_list(self) -> List[Any]: ...
    
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    
    @overload
    def __getitem__(self, key: int) -> Any: ...
    @overload
    def __getitem__(self, key: slice) -> List[Any]: ...